# Matrix Multiplicaiton

In [41]:
import numpy as np

In [42]:
A = np.array([[4,9,9], [9, 1, 6], [9, 2, 3]])
print("Matrix A is a 3 by 3 matrix")

B = np.array([[2,3], [5,7], [4,4]])
print("Matrix B is a 2 by 2 matrix")


Matrix A is a 3 by 3 matrix
Matrix B is a 2 by 2 matrix


In [43]:
# dot product forms a single scalar, while multiplication forms a new matrix

In [44]:
np.matmul(A, B)

array([[ 89, 111],
       [ 47,  58],
       [ 40,  53]])

In [45]:
A @ B

array([[ 89, 111],
       [ 47,  58],
       [ 40,  53]])

In [46]:
# when performing matrix multiplication AB, the number of rows in A has to equal the number of columns in B

In [47]:
try:
    B @ A
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [48]:
# reshaping in numpy

In [49]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])
x.ndim

1

In [50]:
# now we want to shape the matrix in such a way that they can be multiplied, how I would like to look at this is that
# I can make one of them a column vector, that way one is horizontal and the other is vertical.

In [57]:
y_new = y.reshape(3, 1) # from this we can see that x has been turned into a column vector.
y_new


array([[ 4],
       [ 3],
       [-1]])

In [58]:
y

array([ 4,  3, -1])

In [59]:
# now the number of rows equal the number of columns we can now find the product of the matrices

In [60]:
np.matmul(x, y_new)

array([3])

In [62]:
np.dot(x, y_new) # np dot also works for matrix multiplication

array([3])

# Broadcasting

- Broadcasting is when numpy widens an operation to all rows and columns of a matrix/