In [72]:
import numpy as np

In [73]:
# multiplying a vector with a scalar is also known as broadcasting

In [74]:
vector = np.array([1,2])

In [75]:
vector * 10

array([10, 20])

In [76]:
# you can also slice numpy arrays as you slice python lists

In [77]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1254931200.py, line 2)

In [78]:
# you can stack numpy arrays on top of each other either vertically or horizontally to create
# new arrays

# vstack -> stacks vertically, hstack => stacks horizontally, hsplit -> splits an array into several smaller arrays


a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# it takes a tuple of arrays


In [79]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
np.hstack((a,b))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [81]:
np.zeros(3)

array([0., 0., 0.])

In [82]:
np.empty(3)

array([0., 0., 0.])

In [83]:
# the task is to perform matrix operations on a system of linear equations

In [84]:
A = np.array([
    [-1, 3],
    [3, 2]
], dtype=np.dtype(float)) # A is our matrix

In [85]:
b = np.array([7, 1], dtype=np.dtype(float))

In [86]:
# you can evaluate the solution to a system of linear equations using the np.linalg.solve

In [87]:
x = np.linalg.solve(A, b)

In [88]:
x

array([-1.,  2.])

In [89]:
# you can get the determinant by using the .det of the linalg

d = np.linalg.det(A)
d


np.float64(-11.000000000000002)

In [90]:
# You can represent the system as a matrix and then perform row operations on it.

In [91]:
A_system = np.hstack((A, b.reshape((2, 1)))) # in order for two arrays to be stacked, they have to be of the same dimension

In [92]:
A_system

array([[-1.,  3.,  7.],
       [ 3.,  2.,  1.]])

In [93]:
A_copy = A_system.copy()

In [94]:
# We want to perform row operation on the matrix

In [95]:
A_copy

array([[-1.,  3.,  7.],
       [ 3.,  2.,  1.]])

In [96]:
# we want to replace the second row of the array with the first row multiplied by 3 plus itself

In [97]:
A_copy[1] = 3 * A_copy[0] + A_copy[1]

In [98]:
A_copy

array([[-1.,  3.,  7.],
       [ 0., 11., 22.]])

In [99]:
# now we want to divide r2 by the value of the element in the leading diagonal of the matrix

A_copy[1] = 1/11 * A_copy[1]

In [100]:
A_copy

array([[-1.,  3.,  7.],
       [ 0.,  1.,  2.]])

In [102]:
# Graphical representation of the solution, study more on this

In [103]:
A_2 = np.array([
    [-1,3],
    [3.-9]
],dtype=np.dtype(float))

np.linalg.det(A_2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.